targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.graphql.dart
              schema: lib/schema.graphql
              queries_glob: lib/graphql/**.graphql
              # naming_scheme: simple